name = "pepsiman"
account_id = "8b310679d88182c153600aa95457a4eb"
compatibility_date = "2026-07-11"
pages_build_output_dir = "dist-web"

[[d1_databases]]
binding = "LEADERBOARD_DB"
database_name = "pepsiman-leaderboard"
database_id = "baf735a4-2465-4a21-a35f-6c5be38deffb"
